kind = "DojoContract"
class_hash = "0x776076fbdf15df6bcdefafffcbca4d16aa026addc59dc763dd27d341afc4607"
original_class_hash = "0x776076fbdf15df6bcdefafffcbca4d16aa026addc59dc763dd27d341afc4607"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/kageki_duels_systems_stage_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "kageki_duels::systems::stage_actions::actions"
