kind = "DojoContract"
class_hash = "0x178d9e0c99588bdd49ff918f2aab15df8b411522df0beb8f283e8aa3b891bef"
original_class_hash = "0x178d9e0c99588bdd49ff918f2aab15df8b411522df0beb8f283e8aa3b891bef"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/kageki_duels_systems_player_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "kageki_duels::systems::player_actions::actions"
