kind = "DojoContract"
class_hash = "0x5e7ed22bae62ad889675fdb2b7f1927d294b3534f3c9a4f48eebdb1cbca14d2"
original_class_hash = "0x5e7ed22bae62ad889675fdb2b7f1927d294b3534f3c9a4f48eebdb1cbca14d2"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/kageki_duels_systems_player_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "kageki_duels::systems::player_actions::actions"
