kind = "DojoContract"
class_hash = "0x4e68408ac10eb75c35991307bfb3eb6a1f2a60408895a7e13344915a79feb61"
original_class_hash = "0x4e68408ac10eb75c35991307bfb3eb6a1f2a60408895a7e13344915a79feb61"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/kageki_duels_systems_player_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "kageki_duels::systems::player_actions::actions"
