kind = "DojoContract"
class_hash = "0x1b4a2f07b20827e6639056f1ee22c3eb22f27fdaa30fe9ce9a27e924c46eee"
original_class_hash = "0x1b4a2f07b20827e6639056f1ee22c3eb22f27fdaa30fe9ce9a27e924c46eee"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/kageki_duels_systems_stage_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "kageki_duels::systems::stage_actions::actions"
